# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AahC3WqJ2sKhOxwuulgeg5DjkP1fML7g
"""

try:
  # se solicitan símbolo y número de repeticiones 
  simbolo = input("inserte el símblo que desea: ")
  reps = int(input("inserte el número de veces que se realizará el ejercicio: "))

# se realizan las validaciones de lo ingresado
  if (reps <= 0): 
    print("El número debe ser entre 1 y 20!")
  elif(reps > 20):
    print("El número debe ser entre 1 y 20!")
  elif(len(simbolo) == 0):
    print("Debe ingresar un símbolo!")
  elif(len(simbolo) > 1):
    print("Solo debe ingresar un caracter!")

  else:
    # se definen los espacios para pder armar la estructura gráfica
    espacios = '  '*5
    # se crea un ciclo para poder hacer las repeticiones e impreisones según la información ingresada por el usuario
    for i in range (1, reps + 1):
      valora=simbolo*i
      valorb=simbolo*(reps-i+1)
      valor1="{0:<{vreps}}".format(valora,vreps=reps)
      valor2="{0:>{vreps}}".format(valorb,vreps=reps)
      valor3="{0:<{vreps}}".format(valorb,vreps=reps)
      valor4="{0:<{vreps}}".format(valora,vreps=reps)
      print(valor1+espacios+valor2+espacios+valor3+espacios+valor4)

     # excepción al ingresar algún dato erróneo 
except (ValueError):
  print("valores ingresados inválidos")