# -*- coding: utf-8 -*-
"""Ejercicio03-HT2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w3rXmRpjIDfqlr83_BM2KEwibc0KCFSr

**EJERCICIO 03**
"""

# i es definido como el número menor solicitado al usuario
# j es definido como el número mayor
try:
  j = int(input("Por favor ingrese el número mayor del rango a calcular:"))
  if (j > 0): # se hace la validación que el número sea positivo mayor a cero
    i = int(input("Por favor ingrese el número menor del rango a calcular:")) #se solicita el número menor para hacer el cálculo y se valida con un if que esto sea verdadero
    if(j > i):
        suma = 0
        for k in range(i, j + 1): # se crear el ciclo for para el rango de los números ingresados y se acumula la suma 
          suma = suma + k
        print(f"La suma desde {j} hasta {i} es {suma}") # se muestra la respuesta de la suma 
    else:
        print("El valor ingresado no es correcto o no es menor al primer número.")   #else en el caso de que el número menor no sea correcto
  else: 
    print("El valor ingresado no es válido. Inténtelo de nuevo") # else en el caso de que el primer valor no sea mayor a 0

except(ValueError): #excepción para valores no válidos
  print("El valor ingresado no es válido")

finally:
  print ("\n Proceso finalizado")