# -*- coding: utf-8 -*-
"""Ejercicio04-HT2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o72fDebEu9_osY1-fa5EaKpsEwFkAZPY

**EJERCICIO 04**
"""

try:
    # se solicita el número al usuario para hacer el ajercicio
    num = int(input("Ingresa el número positivo que quieres calcular: "))
    factor = []
    i = 1
    if (num > 0 ): # se valida que el número no sea cero
      while i <= num: #se crea el ciclo while para poder realizar el conteo sobre la variable i hasta que sea menor que el ingresado y con el if que el ciclo continúe mientras que el residuo sea 0
        if num % i == 0:
          factor.append(num//i) # se concatenan los números que cumplen con la condición hasta llegar al ingresado. 
          factor.sort()
        i = 1 + i

      print(f"Los factores de {num} son: ") # se configura el texto de salida y se crea un for para poder ir acumulando los resultados y mostrarlos. 
      for j in factor:
        print(f"{j}", end = ",")
    else:
      print ("El valor ingresado no es válido")
except(ValueError):
  print ("El valor ingresado no es válido")