# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bkVLzOO61dqQ3gSI3znegRfQ8uqzrPO9
"""

from datetime import datetime ## se importa la librería datetime para poder obtener la fecha de hoy

 try:
  print("CONOCEREMOS SU EDAD AL DÍA DE HOY!!! \n\n")

  fecha_nacimiento = str(input("Ingrese su fecha de nacimiento en formato dia-mes-año: \n")) # se solicita la fecha en el formato necesario al usuario
  date = datetime.strptime(fecha_nacimiento,'%d-%m-%Y') # se convierte el string a formato de fecha
  hoy = datetime.now() #se obtiene la fecha de hoy 

  # Se realizan los cálculo para obtener la edad en años, meses y días aproximadas 
  edad_a = hoy.year - date.year - ((hoy.month, hoy.day) < (date.month, date.day)) 
  edad_m = abs(date.month - hoy.month - ((hoy.year, hoy.day) < (date.year, date.day)) - 12)
  edad_d = hoy.day - date.day - ((hoy.year, hoy.month) < (date.year, date.month))

  print(f"Su edad actual es de: {edad_a} años, {edad_m} meses, {edad_d} días")
except(ValueError):
  print("Valor ingresado inválido. Intente de nuevo. ")