# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g4bgOCwgBof0j7Z2Qxk5Bt8ZfIE2pcwX

**EJERCICIO # 1 **
"""

try:
  segundos = int(input("Inserte la cantidad de segundos que desea convertir: ")) # se crea el input del usuario y se asigna a la variable que se usará para el cálculo

  minutos = segundos // 60 # se obtiene la cantidad de minutos que representa el monto ingresado y el residuo que queda, que se utilizará más adelante para los segundos totales. 
  segundos_residuo = segundos % 60

  horas = minutos // 60 # Se obtiene el valor en horas, sin decimales, con el cálculo de minutos anterior
  minutos_residuo = minutos % 60 # el restante representa los minutos disponibles 

  print(" {} horas\n {} minutos\n {} segundos".format(horas, minutos_residuo, segundos_residuo)) # se imprime el cálculo final

except (ValueError): # se coloca la excepción en el caso se ingrese un valor inválido
  print ("Los datos no son válidos")
finally:
  print ("Terminó el programa")