# -*- coding: utf-8 -*-
"""Ejercicio02-HT2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DOzizzyQPs9yEKb7AbsyyUkaspgfvVKr

** EJERCICIO 02**
"""

try: 
  calificacion = int(input("Ingrese la nota del alumno para realizar la evaluación:")) # Se solicita la calificación al usuario
  if(calificacion <= 100):  # Se crea un if inicial, para verificar que el dato no exceda la nota más alta
    if(90 < calificacion <= 100):                     # Se hacen las validaciones según el cudaro de rango de notas
      print("La calificación es SOBRESALIENTE")
    elif(70 < calificacion <= 90):
      print("La calificación es MUY BIEN")
    elif(60 < calificacion <= 70):
      diferencia = 71-calificacion # Se hace el cálculo de puntos faltantes para aprobar, en el caso de notas menores a 71
      print("BIEN. Sin embargo, alumno: REPROBADO; Faltaron {} puntos para aprobar".format(diferencia))
    elif(50 <= calificacion <= 60):
      diferencia = 71-calificacion
      print("REGULAR. Alumno: REPROBADO; Faltaron {} puntos para aprobar".format(diferencia))
    else:
      diferencia = 71-calificacion
      print("La calificación es INSIFUCIENTE. Alumno: REPROBADO; Faltaron {} puntos para aprobar".format(diferencia))
  else:
    print("El valor ingresado no es válido. Intente de nuevo")

except(ValueError): #Excepción en el caso de ingreso de valores no válidos
  print("El valor ingresado no es válido. Intente de nuevo")

finally:
  print("\n\n El programa finalizó..")